#!/usr/bin/env python3
"""
Scan 03-corporate-finance/03-5-damodaran-online/ and regenerate:
  - content-index.yaml (schema mirrors 03-2-course-content/lesson-index.yaml)
  - 03-5-damodaran-online/CLAUDE.md
  - one CLAUDE.md per 03-5-1..5 subfolder (doc-index table: file | description)

Run this after every crawl/convert cycle (Phase 3, per the runbook).

Requires: nothing beyond the standard library (writes YAML by hand — no
PyYAML dependency, matching this repo's stdlib-first convention).

Run: python3 scripts/build-damodaran-index.py
"""

import json
import os
import re

ROOT = "03-corporate-finance/03-5-damodaran-online"
CATEGORY_DIRS = {
    "03-5-1-datasets": "datasets",
    "03-5-2-course-materials": "course-materials",
    "03-5-3-papers": "papers",
    "03-5-4-tools": "tools",
    "03-5-5-books": "books",
}


def read_frontmatter(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        text = f.read()
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}
    block = text[4:end]
    meta = {}
    for line in block.splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if value.startswith('"') and value.endswith('"'):
            try:
                value = json.loads(value)
            except Exception:
                value = value.strip('"')
        meta[key.strip()] = value
    return meta


def yaml_str(value):
    if value is None:
        return "null"
    text = str(value)
    if re.search(r'[:#\[\]{}"\']|^\s|\s$', text) or text == "":
        return json.dumps(text)
    return text


def collect_resources():
    resources = []
    for subdir, category in CATEGORY_DIRS.items():
        base = os.path.join(ROOT, subdir)
        if not os.path.isdir(base):
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            md_files = [f for f in filenames if f.endswith(".md") and f != "CLAUDE.md"]
            if not md_files:
                continue
            rel_folder = os.path.relpath(dirpath, ".").replace("\\", "/")
            for md_file in sorted(md_files):
                slug = os.path.splitext(md_file)[0]
                path = os.path.join(dirpath, md_file)
                meta = read_frontmatter(path)
                has_csv = any(f.endswith(".csv") and f.startswith(slug) for f in filenames)
                has_original = any(
                    f.startswith(slug) and os.path.splitext(f)[1].lower() in (".xls", ".xlsx", ".xlsm")
                    for f in filenames
                )
                resources.append({
                    "slug": slug,
                    "category": category,
                    "title": meta.get("title", slug.replace("-", " ").title()),
                    "source_url": meta.get("source_url", ""),
                    "folder": rel_folder,
                    "markdown": True,
                    "csv": has_csv,
                    "original": has_original,
                })
    resources.sort(key=lambda r: (r["category"], r["folder"], r["slug"]))
    return resources


def write_content_index(resources):
    lines = ["resources:"]
    for r in resources:
        lines.append(f"  - slug: {yaml_str(r['slug'])}")
        lines.append(f"    category: {yaml_str(r['category'])}")
        lines.append(f"    title: {yaml_str(r['title'])}")
        lines.append(f"    source_url: {yaml_str(r['source_url'])}")
        lines.append(f"    folder: {yaml_str(r['folder'])}")
        lines.append(f"    files: {{markdown: {str(r['markdown']).lower()}, "
                      f"csv: {str(r['csv']).lower()}, original: {str(r['original']).lower()}}}")
    content = "\n".join(lines) + "\n"
    with open(os.path.join(ROOT, "content-index.yaml"), "w", encoding="utf-8") as f:
        f.write(content)


def write_subfolder_claude_md(subdir, resources):
    base = os.path.join(ROOT, subdir)
    subset = [r for r in resources if r["folder"].startswith(base.replace("\\", "/"))]
    title = subdir.split("-", 2)[-1].replace("-", " ").title()
    lines = [f"# {title}", "", f"Auto-generated by `scripts/build-damodaran-index.py`. "
             f"{len(subset)} resource(s) indexed here.", "", "## Doc Index", "",
             "| File | Description |", "|------|-------------|"]
    for r in subset:
        rel = os.path.relpath(os.path.join(r["folder"], r["slug"] + ".md"), base).replace("\\", "/")
        desc = r["title"]
        if r["source_url"]:
            desc += f" — source: {r['source_url']}"
        lines.append(f"| [{r['slug']}.md]({rel}) | {desc} |")
    os.makedirs(base, exist_ok=True)
    with open(os.path.join(base, "CLAUDE.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def write_root_claude_md(resources):
    counts = {}
    for r in resources:
        counts[r["category"]] = counts.get(r["category"], 0) + 1

    lines = [
        "# Damodaran Online Archive",
        "",
        "Local archive of Damodaran's website (pages.stern.nyu.edu/~adamodar/) — "
        "datasets, course materials, research papers, Excel tools, and book companions "
        "— converted to Claude-readable markdown.",
        "",
        f"**Status: built.** {len(resources)} resources indexed across "
        f"{len(counts)} categories. Regenerated by `scripts/build-damodaran-index.py` "
        "after each crawl/convert cycle.",
        "",
        "## Doc Index",
        "",
        "| File | Description |",
        "|------|-------------|",
        "| [crawl-and-conversion-runbook.md](crawl-and-conversion-runbook.md) | "
        "Self-contained runbook: phases, script specs, scale gates, and conventions "
        "for building this archive. |",
        "| [content-index.yaml](content-index.yaml) | Master resource index — every "
        "converted file, its category, source URL, and available formats. |",
    ]
    for subdir, category in CATEGORY_DIRS.items():
        if os.path.isdir(os.path.join(ROOT, subdir)):
            lines.append(f"| [{subdir}/CLAUDE.md]({subdir}/CLAUDE.md) | "
                         f"{category.replace('-', ' ').title()} — {counts.get(category, 0)} resource(s). |")
    lines += [
        "",
        "## Notes for future sessions",
        "",
        "- Blog posts are NOT archived here — they live in "
        "[`../03-4-blogs/posts/`](../03-4-blogs/posts/) (~680 posts)",
        "- Videos are never downloaded — stub `.md` files with external URLs only",
        "- Some PDF pages may be marked `needs_vision` in `scripts/convert-progress.json` "
        "if they were converted without `ANTHROPIC_API_KEY` set — re-run "
        "`scripts/convert-damodaran-pdfs.py` with the key set to backfill those.",
    ]
    with open(os.path.join(ROOT, "CLAUDE.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    resources = collect_resources()
    write_content_index(resources)
    for subdir in CATEGORY_DIRS:
        write_subfolder_claude_md(subdir, resources)
    write_root_claude_md(resources)
    print(f"Indexed {len(resources)} resources. Wrote content-index.yaml, "
          f"{ROOT}/CLAUDE.md, and per-subfolder CLAUDE.md files.")


if __name__ == "__main__":
    main()
