---
title: "Valproject4"
status: active
owner: weprintmoney
created: 2026-09-02
last_updated: 2026-09-02
source_url: https://pages.stern.nyu.edu/~adamodar/pdfiles/eqprojects/valproject4.pdf
---

# **Equity Valuation Project**

**Odhran Maguire -** Costco Wholesale Corporation (NASDAQ: COST)

**Gaurav Gupta -** Warner Bros Discovery Inc

**Leyan Dai** - BYD company limited

**Neal Haulsey** - Salesforce, Inc.

**Leandra Mendez** - Netflix, Inc

| Company     |                 | Price    | DCF value | Pricing  | Recommendation |
|-------------|-----------------|----------|-----------|----------|----------------|
| Costco      | Wholesale       |          |           |          |                |
|             |                 | \$498.85 | \$464.59  | \$545.00 | Buy            |
| Warner      | Bros Discovery  |          |           |          |                |
|             |                 | \$12.89  | \$19.09   | \$26.29  | Buy            |
| BYD         | company limited | ¥252.70  | ¥309.00   | ¥274.66  | Buy            |
| Salesforce, | Inc.            | \$188.59 | \$110.80  | \$135.71 | Sell           |
| Netflix,    | Inc             | \$322.76 | \$124.04  | \$304.65 | Sell           |

#### Overall Assumptions & Requirements:

Non-US Company: BYD company limited

High-growth: Warner Bros Discovery, BYD company:

Money-losing: Warner Bros Discovery

Service firm: Netflix & Warner Bros Discovery (streaming services) & Salesforce (SaaS)

## WACC assumptions across DCF:

Risk-free rate on date of DCF Valuation:

- US 10-year yield on a US Treasury Bond (3.4% 3.6%)
- China: Government bond risk of default (2.02%)

Equity Risk Premium:

- Operating Regions approach estimating for equity risk premiums.

Beta

- Operating Segments ground-up beta used for company betas.

# **Costco Wholesale**

#### Company overview / Story for DCF:

Costco Wholesale Corporation (NASDAQ: COST) primarily operates membership retail warehouses across the United States, Canada, Mexico and other international countries.Their online retail and gasoline businesses are still in their relative infancy and the firm generates the majority of its revenue in brick and mortar warehouse stores. The company is currently focused on international expansion, online growth, as well as establishing brand loyalty in the US. These segments will need higher levels of reinvestment but should contribute to moderate levels of revenue growth and exposure to new markets will improve Costo's slim margins in the long-term. Costco benefits from significant economies of scale and is positioned as a leader in the discount retailing market; the risk associated with the firm is relatively low given that they can absorb cost increases and drive out competition in an oligopoly style market.

## **Intrinsic DCF Valuation Model:**

#### Model Assumptions:

| The Assumptions      |              |                 |           |       |               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|----------------------|--------------|-----------------|-----------|-------|---------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                      | Base year    | Next year       | Years 2-5 |       | After year 10 | Link to story                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| Revenues (a)         | \$234,390.00 | 12.0%           | 12.00%    |       | 3.60%         | Revenue Growth will stay strong at around 12% in the next 5 years as Costco expands their international warehouse wholesaling business, grows their e-commerce business, along with an expansion of their online presence. Their higher-than-in industry average level of growth reflects thei acquisition of market share in international consumer staple markets. 12% growth in the next 1-5 years reflects a sustainable growth rate in which Costco can grow without minimizing operating margins; a primary goal of senior management.                                                                                                                      |
| Operating margin (b) | 3.39%        | 3.0%            |           |       | 5.00%         | Their warehouse wholesaling business in Europe will be less exposed to competition than the US warehouses. Costco is focusing on establishing brand loyalty and improving on the current renewal rate on their annual memberships. The expansion of the e-commerce and gasoline businesses will offset the positive effect of increasing brand loyalty in the short-term. However, as those businesses mature, we should expect margins to slowly increase towards 5% in the long-term. While brand loyalty may be increasing, consumers tend to be fickle in the consumer staples sector, especially given the fact that Costco is a discount retailer.          |
| Tax rate             | 24.50%       |                 | 24.50%    |       | 25.00%        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| Reinvestment (c)     |              | 10.00           | 8.00      | 10.00 | 30.00%        | Costco's current sales to capital ratio is 12. However, as Costco expands through the acquisition of additional warehouses, the efficiency of invested capital will decrease. This reflects the reality of their need to establish new warehouse stores in less attractive sites and areas. Revenues generated per unit of capital invested abroad will be low until demand is stimulated. In addition, the expansion of their online retail business will come with significant customer acquisition costs. Due to reasons outlined above, Costco will experience a permanent decline in their sales to capital ratio as their business lines expand and mature. |
| Return on capital    | 32.45%       | Marginal ROIC = | 56.62%    |       | 12.00%        | I overode the assumption that the firm can only earn their cost of capital in terminal year. Market for Costco is a traditional oligopoly market with huge barriers to entry.Costco has significant competitive advantages that will not be mitigated easily.                                                                                                                                                                                                                                                                                                                                                                                                     |
| Cost of capital (d)  |              |                 | 8.20%     |       | 9.54%         | High(ish) percentage revenues generated in Mexico inflate the cost of capital.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |

| The Cash Flows |              |                  |             |             |              |             |
|----------------|--------------|------------------|-------------|-------------|--------------|-------------|
|                | Revenues     | Operating Margin | EBIT        | EBIT (1-t)  | Reinvestment | FCFF        |
| 1              | \$262,516.80 | 3.00%            | \$7,875.50  | \$5,946.01  | \$2,812.68   | \$3,133.33  |
| 2              | \$294,018.82 | 3.80%            | \$11,172.72 | \$8,435.40  | \$3,937.75   | \$4,497.65  |
| 3              | \$329,301.07 | 4.20%            | \$13,830.65 | \$10,442.14 | \$4,410.28   | \$6,031.85  |
| 4              | \$368,817.20 | 4.60%            | \$16,965.59 | \$12,809.02 | \$4,939.52   | \$7,869.51  |
| 5              | \$413,075.27 | 5.00%            | \$20,653.76 | \$15,593.59 | \$4,425.81   | \$11,167.78 |
| 6              | \$454,382.79 | 5.00%            | \$22,719.14 | \$17,130.23 | \$4,130.75   | \$12,999.48 |
| 7              | \$490,733.42 | 5.00%            | \$24,536.67 | \$18,476.11 | \$3,635.06   | \$14,841.05 |
| 8              | \$520,177.42 | 5.00%            | \$26,008.87 | \$19,558.67 | \$2,944.40   | \$16,614.27 |
| 9              | \$540,984.52 | 5.00%            | \$27,049.23 | \$20,313.97 | \$2,080.71   | \$18,233.26 |
| 10             | \$551,804.21 | 5.00%            | \$29,021.21 | \$21,062.66 | \$1,081.97   | \$19,610.69 |
| Terminal year  | \$562,840.29 | 5.00%            | \$28,142.01 | \$21,106.51 | \$3,517.75   | \$17,588.76 |

#### Intrinsic Value:

| Terminal value                      | \$296,107.06 |                                 |  |
|-------------------------------------|--------------|---------------------------------|--|
| PV(Terminal value)                  | \$135,600.56 |                                 |  |
| PV (CF over next 10 years)          | \$67,886.42  |                                 |  |
| Value of operating assets =         | \$203,486.98 |                                 |  |
| Adjustment for distress             | \$0.00       | Probability of failure = 0.00%  |  |
| - Debt & Minority Interests         | \$9,068.00   |                                 |  |
| + Cash & Other Non-operating assets | \$11,209.00  |                                 |  |
| Value of equity                     | \$205,627.98 |                                 |  |
| - Value of equity options           | \$0.00       |                                 |  |
| Number of shares                    | 442.60       |                                 |  |
| Value per share                     | \$464.59     | Stock was trading at = \$498.85 |  |

I found an intrinsic value of **\$464.59 per share.** The stock is currently trading at \$498.85. All numbers in the above valuation are reported in millions (\$).

## **Relative Sector Pricing:**

#### Sector Evaluation: Consumer Staples

Multiple Used: Enterprise Value / Sales. Costco Wholesale is a main player in the Consumer Staples sector. The profitability of Costco and their competitors is primarily driven by after-tax operating margins, revenue growth, and risk. The EV/Sales multiple provided us with the best regression with the highest R-squared.

#### Establishing a regression analysis:

We ran a multi-variable log-log regression across in the Consumer Staples sector with positive operating income (n = 88). We found a log-log relationship between EV/Sales and operating margins. While this eliminated companies with negative margins, we were still left with a sizable sample size of the most comparable firms.

#### Relationship between the variables:

From this scatterplot below, we can see the relationship between log(Margins) and the log(EV/Sales).

![](_page_2_Figure_10.jpeg)

![](_page_2_Figure_11.jpeg)

Predicted EV/Sales Equation:  $\ln(EV) \sim \text{Growth rate} + \ln(\text{Operating Margin}) + \text{Debt-to-Capital Ratio}$ .

Costco's current EV/Sales is 0.92. Our predicted EV/Sales using the log-log regression was 1.02, assuming a growth rate of 6.69%, an operating margin of 3.39%, an effective tax rate of 24.9% and a Debt to Capital ratio of 28.6. I used the predict function in R and did not explicitly detail the calculation due to the complexity of log-log transformations.

Given that Costco's current revenues are \$234,390M, our fitted Enterprise Value is \$239,078M. Incorporating cash and netting Debt, we are left with a **price of \$545 per share**.

Price per share:  $\$234,390 * 1.02 - 9086 + 11209 = 241200.8 / 442.6 = \$545 \text{ per share}$ 

The 95% confidence interval associated with this estimated price is [\$470.86, \$624.44]. Our EV/Sales model indicates that Costco is **underpriced** relative to comparable Consumer staples stocks.

## Relative Market Pricing:

We used a similar regression to price Costco against the overall US market. Per your advice, I exploited the log-log relationship between EV/Sales and Operating Margins, despite the reduction in sample size to 1562 and potential biasing of the sample.

### Regression output:

```
## =====
##                              Dependent variable: -----
##                              log(EV/Sales) -----
## -----
## Growth Rate (2yr)           0.028***
##                             (0.002)
## log(Operating Margin)        0.659***
##                             (0.019)
## Constant                   -0.994***
##                             (0.056)
## -----
## Observations                1,562
##                             0.459
## Adjusted R2                0.458
## Residual Std. Error        0.730 (df = 1559)
## F Statistic               661.816*** (df = 2; 1559)
## =====
## Note:                     *p<0.1; **p<0.05; ***p<0.01costcom <- data.frame(Margin = 3.39, Growth = 6.59, TAX = 24.9, DFR = 28.6)
exp(predict(market, costcom, interval = 'confidence', level = 0.95))##           fit          lwr     upr
## 1 0.9938434 0.9334049 1.058195
```

Regression Equation:  $\log(\text{EVSales}) \sim \text{Growth Rate} + \ln(\text{Operating Margins})$ 

The predicted EV/Sales for Costco using this market model was 0.99, after adjusting for revenue growth (6.9%) and operating margin (3.39%). Using that predicted Enterprise value estimate, **we priced Costco**

**at \$529.12 relative to the overall market**. The 95% confidence interval associated with this price is [\$497.34, \$566.19]

## **Recommendation: BUY**

My intrinsic valuation reflected an overvalued business with moderate growth and slim margins. However, the path of Costo's online business is relatively unclear, and the plans for future expansion are not defined. Logically, I think that their strategic focus will be on semi-perishable domestic goods. Other product offerings will meet direct competition from Amazon in an online retail market. While intrinsically, I feel that the stock is overvalued according to their current margins and short-term future plans, the uncertainty of the future profitability of their online and international businesses means that selling the stock would be a mistake. I could not incorporate this intuition into my intrinsic valuation model, given that there is no concrete indication that senior management aims to progress in this way. Given that the stock is currently underpriced (\$545) relative to the comparable firms in its sector, I think that now might be a good time to buy and hold in the long-term before the stock price is inflated due to the upcoming recession. The online grocery market is still in its infancy but it's a risk I am willing to take.

# **Warner Bros Discovery, Inc**

#### Company Overview / Story for DCF:

Warner Bros Discovery Inc (NASDAQ: WBD) is a global entertainment and media firm formed after the merger between WarnerMedia and Discovery in 2022. Some of the revenue-generating activities for Warner Bros and Discovery will be through the selling of advertisements on TV networks and digital platforms, charging distribution fees to cable and offering direct-to-consumer services. Large-scale restructuring means that the firm is currently losing money but the establishment of their mega-streaming service (MAX), will provide significant revenue growth and the leverage of WB's intellectual property will widen their margins in the long-term. We expect MAX to acquire significant market share in the near future and will establish itself as a leader in the streaming services industry. However, this growth will require significant re-investment, evidenced by a low sales/capital ratio (normal for the industry). In terms of risk, the firm has significantly reduced their high levels of debt and has become relatively more stable. Given the firm's extensive library of intellectual property (Harry Potter etc.), the risk associated with the firm's cash flows are relatively low and the firm is well positioned across the entertainment industry globally. I will expand more on each driver below.

## **Intrinsic DCF Valuation Model:**

#### Model assumptions:

|                      | Base year   | Next year       | Years 2-5 | Years 6-10 | After year 10 | Link to story                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|----------------------|-------------|-----------------|-----------|------------|---------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Revenues (a)         | \$33,817.00 | 45.0%           | 35.00%    |            | 3.60%         | Overall, the merger between Warner Bros and Discovery Inc created 3 main segments; production studios, TV networks and streaming services. We've projected growth rates which reflects significant increases in revenue and market share in the streaming industry from the merging of HBO Max and Discovery into one mega-streaming platform. This is well above the projected entertainment sector growth rate of 8.5%. The consolidation of these two platforms will put their streaming segment in a position to directly compete with Netflix. In addition to that, the establishment of an advertising-based free service will also rapidly expand revenues as the platform gains traction. |
| Operating margin (b) | -21.79%     | -5.0%           |           |            | 15.00%        | Warner Bros Discovery's current operating margins are negative due to large scale restructuring, following the merger in April 2022. These issues should clear up by next year; senior management are currently on a cost-cutting rampage. We've projected a negative operating margin for this year, but following that we expect profitability to pick up and move towards 15% in year 10. Operating Margins of 15% represent the businesses ability to leverage their unmatched intellectual property and the establishment of MAX as a powerhouse in the streaming business.                                                                                                                  |
| Tax rate             | 19.00%      |                 | 19.00%    |            | 25.00%        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| Reinvestment (c)     |             | 1.10            | 1.10      | 1.10       | 39.82%        | The efficiency of invested capital in the entertainment business tends to be relatively low, given high production costs and expenses associated with producing and distributing content. However, we feel that Warner Bros Discovery library of intellectual property and brand name television will reduce customer acquisitions costs and lead to a higher efficiency of invested capital than other firm's in the industry. That being said, the Sales/Capital is still low at 1.1.                                                                                                                                                                                                           |
| Return on capital    | -7.95%      | Marginal ROIC = |           | 16.56%     | 9.04%         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| Cost of capital (d)  |             | 8.81%           |           |            | 9.04%         | Given WB's high level of debt, their cost of capital is quite high, however it has been significantly reduced in the last year and is now at a point where senior management are more content.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |

| Price Cost Row |              |                  |             |             |              |              |
|----------------|--------------|------------------|-------------|-------------|--------------|--------------|
|                | Revenues     | Operating Margin | EBIT        | EBIT (1-t)  | Reinvestment | FCFF         |
| 1              | \$49,034.65  | -5.00%           | -\$2,451.73 | -\$2,451.73 | \$15,601.93  | -\$18,053.67 |
| 2              | \$66,196.78  | 0.00%            | \$0.00      | \$0.00      | \$21,062.61  | -\$21,062.61 |
| 3              | \$89,365.65  | 2.50%            | \$2,234.14  | \$2,234.14  | \$28,434.52  | -\$26,200.38 |
| 4              | \$120,643.63 | 5.00%            | \$6,032.18  | \$4,927.41  | \$38,386.61  | -\$33,459.20 |
| 5              | \$162,868.90 | 7.50%            | \$12,215.17 | \$9,894.29  | \$42,523.59  | -\$32,629.30 |
| 6              | \$209,644.84 | 10.00%           | \$20,964.48 | \$16,729.66 | \$42,767.55  | -\$26,037.89 |
| 7              | \$256,689.15 | 12.50%           | \$32,086.14 | \$25,219.71 | \$37,709.97  | -\$12,490.26 |
| 8              | \$298,170.11 | 15.00%           | \$44,725.52 | \$34,617.55 | \$26,781.10  | \$7,836.45   |
| 9              | \$327,629.32 | 15.00%           | \$49,144.03 | \$37,448.03 | \$10,722.41  | \$26,725.62  |
| 10             | \$339,423.98 | 15.00%           | \$50,913.60 | \$38,185.20 | \$11,108.42  | \$27,076.78  |
| Terminal year  | \$351,643.24 | 15.00%           | \$52,746.49 | \$39,559.86 | \$15,753.93  | \$23,805.94  |

|                                     | <i>The Value</i> |                                |
|-------------------------------------|------------------|--------------------------------|
| Terminal value                      | \$437,609.12     |                                |
| PV(Terminal value)                  | \$186,884.20     |                                |
| PV (CF over next 10 years)          | -\$94,574.76     |                                |
| Value of operating assets =         | \$92,309.45      |                                |
| Adjustment for distress             | \$0.00           | Probability of failure = 0.00% |
| - Debt & Minority Interests         | \$49,368.00      |                                |
| + Cash & Other Non-operating assets | \$3,731.00       |                                |
| Value of equity                     | \$46,672.45      |                                |
| - Value of equity options           | \$291.84         |                                |
| Number of shares                    | 2,430.00         |                                |
| Value per share                     | \$19.00          | Stock was trading at = \$12.89 |

Using the above assumptions for revenue growth, operating margins, growth and reinvestment, I found an intrinsic **value per share of \$19.09.** The stock is currently trading at \$12.89.

## **Relative Sector Pricing:**

We used P/BV as the pricing multiple for this regression as it produced the highest R-squared value for the Communication Services sector. Our sample size was reduced to 62 due to the lack of estimated growth rates of most of the firm's on capital IQ. However, we felt that the sample was large enough and also comprised the most comparable firms in the sector.

#### Negative Earnings strategy:

As previously mentioned in the DCF part of our analysis, the firm's operating margin of -21.5% reflects a firm in the process of dealing with a messy acquisition and large-scale structuring. As we move further into this year, we expect that the firm's operations will stabilize and operating metrics will be more reflective of the firm in the longer-term. Using this logic, we decided to use the firm's growth and return on equity in year 10 when arriving at our predicted price-to-book ratio - discounting it back at the cost of equity. While this may be an imperfect strategy, we felt it was the best way to price the business.

| ## |                     |                             |
|----|---------------------|-----------------------------|
| ## |                     |                             |
| ## | Dependent variable: |                             |
| ## |                     |                             |
| ## | PB                  |                             |
| ## |                     |                             |
| ## | Growth              | -0.002                      |
| ## |                     | (0.014)                     |
| ## |                     |                             |
| ## | RE                  | 0.173***                    |
| ## |                     | (0.017)                     |
| ## |                     |                             |
| ## | Beta                | 2.403**                     |
| ## |                     | (1.170)                     |
| ## |                     |                             |
| ## | Constant            | -0.729                      |
| ## |                     | (1.469)                     |
| ## |                     |                             |
| ## |                     |                             |
| ## | Observations        | 62                          |
| ## | R2                  | 0.657                       |
| ## | Adjusted R2         | 0.640                       |
| ## | Residual Std. Error | 4.617 (df = 58)             |
| ## | F Statistic         | 37.074*** (df = 3; 58)      |
| ## |                     |                             |
| ## | Note:               | *p<0.1; **p<0.05; ***p<0.01 |

### Regression Equation: P/B ~ Growth + Return on Equity + Beta

Despite the lack of statistical significance on beta and growth, their removal resulted in a significant reduction in the model's R-squared so we retained these variables in the regression. Using an estimated eps growth rate of 3.6%, return on equity of 15% and the firm's current beta, our regression produced a predicted PB (year 10) of 5.5. Using this value, we found an estimate of year 10's equity value and

discounted it back at the cost of equity found in our DCF valuation (15.44%). Using this strategy, we found an **estimated price of \$26.29**, indicating that Warner Bros stock is currently underpriced relative to the other firm's in the sector.

PBV = 0-0.729 -0.002\*3.6 + 2.403 \* 1.48 + 0.173 \*15 = 5.5

Price per share = 5.5 \* 47095 / 2430 = **\$26.29 per share**

## **Relative Market Pricing:**

I used the market regression provided on your website for the US market, with a r-squared of 0.369. I used the same strategy as above regarding the firm's current negative margins.

PBV= 2.32 + 4.60 gEPS - 1.33 Beta + 8.90 ROE + 0.80 Payout Ratio

PBV = 2.32 + 4.60 \* 0.03 - 1.33 \* 1.48 + 8.90 \* 0.1544 + 0.80 \* 0 = 1.81

Using this PB ratio and a book value of equity of 47095, we arrived at a **price per share of \$35.08.**

## **Recommendation: BUY**

Based on the DCF Valuation and relative pricing, I think that Warner Bros Discovery is a buy right now. The current indications from senior management suggest that the firm will become profitable in the near future, and I think that the market has underestimated the firm's potential growth from the megastreaming service. Not only will growth be forged by customer acquisition, but also by the firm's ability to increase subscription costs when it fully establishes itself and unveils its unparalleled IP. Netflix is in trouble! Both my DCF valuation (\$19) and pricing (\$26) reflect the undervaluation of the company, and now is a great time to buy.

# **BYD Company Limited**

## Company Overview / Story for DCF:

BYD Company Limited, together with its subsidiaries, engages in the research, development, manufacture, and sale of automobiles and related products in China and internationally. The company operates through three segments: Automobiles, Automobile-Related Products and Other Products; It is a market leader in the Chinese automobile industry with a controlling market share. Although it will require high levels of reinvestment, the firm's R&D will continue to generate significant levels of revenue growth and the firm's profitability will improve (somewhat marginally) as the business matures. The firm is well positioned to take full advantage of the growth in popularity of electric vehicles. In terms of risk, the EV market is rapidly growing as the global economy moves towards carbon-neutrality and sustainability - the risk associated with the cash flows is relatively low given that BYD is an established market leader and will only become more profitable with further development.

## **Intrinsic DCF Valuation Model:**

The company was valued in Chinese Yuan, and the current risk-free rate is 2.02%, the assumed stable current growth rate of the economy.

#### Model assumptions:

| BYD Company Limited                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |               |               |           |            |               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | May - 23 |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------|---------------|-----------|------------|---------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|
| BYD is the first and largest automobile company in China that introduces electronic cars to the market. It has a huge lead on electronic cars in China, having a market share of 27%. Benefiting from the recovery of COVID and the cutting prices, I believe BYD will improve its production and gain profits. The boost of technology and people's increasing need for intelligent products also pushes BYD to gain an advantage against traditional vehicles. However, the investment in research and development would not be low considering its wide range of business and the need to innovate. It is also benefiting from Chinese government's policy of promoting electronic cars. |               |               |           |            |               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |          |
| <i>The Assumptions</i>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |               |               |           |            |               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |          |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | Base year     | Next year     | Years 2-5 | Years 6-10 | After year 10 | Link to story                                                                                                                                                                                                                                                                                                                                                                                                                                                   |          |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |               |               | ←         |            |               | BYD's revenue growth rate is 96% this year with government subsidy. Its early position in the EV industry has earned it great market share (27% in 2022) and the promising future of the EV market will deliver large revenue. It's cutting prices and the government will stop offering subsidies next year, so I set next year's growth rate to 80% and 24% in years 2-5. After year 10, I believe it will follow the economy and grow at the risk free rate. |          |
| Revenues (a)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | ¥ 424,060,635 | 80.0%         | 24.00%    |            | 2.02%         | This low operating margin reflects an organization with the majority of revenue generated from automobile manufacturing and sales. Right now, it is in the process of reducing its prices, however, as the business matures. I expect that they will become more operationally efficient. However, even small gains will be difficult so I set operating margins to 6% next year and 7% after year 10.                                                          |          |
| Operating margin                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 8.25%         | 6.0%          |           |            | 7.00%         | Global tax rate                                                                                                                                                                                                                                                                                                                                                                                                                                                 |          |
| Tax rate                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | 15.97%        |               | 15.97%    | ←          | 25.00%        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |          |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |               |               |           |            |               | BYD's sales to capital rate is 3.66 now. BYD is still in the process of developing new technology; car batteries, energy storage and solar panels. In the short-term, I expect the efficiency of investment to fall to reflect this additional reinvestment and innovation. As this business matures, I expect the efficiency of invested capital to mature and the sales/capital ratio will return to current levels in the long-run.                          |          |
| Reinvestment (c)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 3.00          |               | 2.80      | 3.50       | 16.61%        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |          |
| Return on capital                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | 25.40%        | Marginal ROIC |           | 21.83%     | 12.14%        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |          |
| Cost of capital (d)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |               |               | 8.60%     | ←          | 9.50%         | Cost of capital close to median company                                                                                                                                                                                                                                                                                                                                                                                                                         |          |

*The Cash Flows*

|               | Revenues        | Operating Margin | EBIT          | EBIT (1-t)    | Reinvestment  | FCFF    |
|---------------|-----------------|------------------|---------------|---------------|---------------|---------|
| 1             | ¥ 763,309,143   | 6.00%            | ¥ 45,798,549  | ¥ 38,484,103  | ¥ 113,082,836 | -74,596 |
| 2             | ¥ 946,503,337   | 6.20%            | ¥ 58,683,207  | ¥ 49,310,963  | ¥ 65,426,498  | -16,115 |
| 3             | ¥ 1,173,664,138 | 6.30%            | ¥ 73,940,841  | ¥ 62,131,814  | ¥ 81,128,857  | -18,992 |
| 4             | ¥ 1,455,343,531 | 6.40%            | ¥ 93,141,986  | ¥ 78,266,361  | ¥ 100,599,783 | -22,338 |
| 5             | ¥ 1,804,625,979 | 6.50%            | ¥ 117,300,689 | ¥ 98,566,699  | ¥ 99,794,985  | -1,225  |
| 6             | ¥ 2,158,390,419 | 7.50%            | ¥ 161,871,863 | ¥ 133,096,339 | ¥ 101,075,554 | 32,021  |
| 7             | ¥ 2,486,603,900 | 7.37%            | ¥ 183,380,628 | ¥ 147,470,030 | ¥ 93,775,280  | 53,693  |
| 8             | ¥ 2,755,395,835 | 7.25%            | ¥ 199,761,463 | ¥ 157,035,752 | ¥ 76,797,696  | 80,236  |
| 9             | ¥ 2,932,093,859 | 7.12%            | ¥ 208,909,168 | ¥ 160,454,394 | ¥ 50,485,150  | 109,966 |
| 10            | ¥ 2,991,204,871 | 7.00%            | ¥ 209,384,341 | ¥ 157,038,256 | ¥ 16,888,861  | 140,145 |
| Terminal year | ¥ 3,051,507,561 | 7.00%            | ¥ 213,605,529 | ¥ 160,204,147 | ¥ 26,603,918  | 133,601 |

*The Value*

| Final value                       | ¥ 1,785,144,700 |                                |  |  |  |
|-----------------------------------|-----------------|--------------------------------|--|--|--|
| Terminal value                    | ¥ 763,032,832   |                                |  |  |  |
| CF over next 10 years             | ¥ 87,847,042    |                                |  |  |  |
| Probability of operating assets = | ¥ 850,879,873   |                                |  |  |  |
| Statement for distress            | ¥ -             | Probability of failure = 0.00% |  |  |  |
| Sob & Minority Interests          | ¥ 23,107,232    |                                |  |  |  |
| Cash & Other Non-operating assets | ¥ 71,809,387    |                                |  |  |  |
| Probability of equity             | ¥ 899,582,028   |                                |  |  |  |
| Value of equity options           | ¥ 25,163        |                                |  |  |  |
| Per of shares                     | ¥ 2,911,143.00  |                                |  |  |  |
| Total per share                   | ¥ 300.00        |                                |  |  |  |

Using the above assumptions for growth, operating margins and reinvestment, I found an intrinsic value of **¥309 per share**.

## Relative Sector Pricing:

```
call:
1m(formula = EV_to_sales ~ operating_margin + DFR, data = evs_data)Residuals:
  Min          1Q     Median                3Q              Max
-2.8605 -0.8782 -0.0168  0.7311    6.3091Coefficients:
                                Estimate Std. Error t value Pr(>|t|)
(Intercept)             0.1710            0.4117        0.415     0.67899
operating_margin        25.4419            3.2061        7.935 1.08e-11 ***
DFR                     -2.0532            0.7526    -2.728    0.00783 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1Residual standard error: 1.297 on 80 degrees of freedom
Multiple R-squared:  0.4962,                Adjusted R-squared:  0.4836
F-statistic:    39.4 on 2 and 80 DF,  p-value: 1.23e-12
```

Multiple used: EV/Sales, because it gives the highest R square value, which is 0.4836 among the different multiples.

Comparable firms: Automobile and Components companies (sample size=83)

Control tool: I ran a regression of EV/Sales against operating margin and DFR across the 83 firms. I eliminated the growth rate and payout ratio because they were not statistically significant.

Formula:  $EV/Sales=0.17+25.44*operating\_margin-2.05*DFR(R-squared=48.36\%)$ 

BYD's EV/Sales= $0.17+25.44*0.0825-2.05*0.216=1.81$ 

BYD's EV= $1.81*\$424,061=\$767550$ 

BYD's Pricing Per Share= $(767550+66,715-34,735)/2,911=\$274.66$ 

## Relative Market Pricing:

I used the market regressions from your website to price the firm against the global market, using the EV/Sales multiple. The regression has an R-squared value of 0.178.

 $EV/Sales = 2.68 + 2.50 g + 8.10 Oper Margin + 2.10 DFR - 5.10 Tax rate$ 

 $EV/Sales=2.68 + 2.50*24\% + 8.10 *8.25\% + 2.10 *0.216 - 5.10*15.97\%=3.59$ 

 $Price Per Share=(3.59*424,061+66,715-34,735)/2,911=\$533.96$ 

## Recommendation: BUY

As both the intrinsic (**¥309)** and relative pricing (**¥274.66)** found that BYD is undervalued, my recommendation is to buy. It is one thing that the electric cars industry is very likely to have a bright future with the research and development of new technologies. It is another that BYD is going to benefit a lot from its early acquisition of market share and the policy of cutting prices, which allows BYD to improve production in the long run. Similar to how we discussed optionality in class, the true potential growth of the EV industry is relatively unknown and for a company with a huge focus on research and development - the full extent of their potential cannot be incorporated into an intrinsic valuation. So while I trust my current DCF Valuation of **¥**309 per share, I think the stock price has the potential to grow significantly above my estimates over the next decade. This reiterates my reasoning to buy the stock.

# **Salesforce, Inc.**

#### Overview / Story for DCF:

Salesforce, Inc. (NYSE:CRM) is a market leader in the Customer Relationship Management (CRM) space, which allows businesses to manage its interactions with customers, analyze data from them, and gather insights to increase consumer loyalty and revenue. They also have recently been engaging in Artificial Intelligence through EinsteinGPT, the world's first generative AI for CRM applications. Salesforce has rapidly grown in the last 20 years and is fully established as the market leader in the US. Salesforce is still experiencing high levels of potential growth as their products are gaining traction with global clients overseas. However, senior management has turned their head away from growth and is now focusing on profitability (intention to reward shareholders). Operating margins should increase significantly over the next decade as management pursues this strategy. Reinvestment rates in the sector are relatively low, however, demand in international markets has been self-driven with lower customer acquisition cost. With this in mind, sales/capital will increase in the long-term but still stay within industry norms. As the firm pivots towards focusing on profitability, the level of risk in the operations will fall. However, it's likely that they will be exposed to competition as more firms enter the space.

## **Intrinsic DCF Valuation Model:**

| The Assumptions     |             |               |           |            |               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|---------------------|-------------|---------------|-----------|------------|---------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                     | Base year   | Next year     | Years 2-5 | Years 6-10 | After year 10 | Link to story                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| Revenues (a)        | \$31,352.00 | 25.0%         | 20.00%    |            | 3.60%         | Over the last 10 years, Salesforce has established itself as the primary market leader in the Customer Relationship Management space, growing at an YOY of 50%. While we expect this to slow as the company matures, they are still in the process of expanding their overseas client base which should keep revenue growth high as they acquire more market share abroad. As they exhaust these international markets, their operations will fully mature and we expect them to grow at the market's stable rate.      |
| Operating margin    | 10.54%      | 10.0%         |           |            | 20.00%        | Improving their operating margins has become a primary focus of the firm's management. As Salesforce moves from a young high-growth to a mature market company, they will establish healthy operating margins of around 20% in the longer term. This reflects the company's established market share and inability of other firms to fiercely challenge them.                                                                                                                                                           |
| Tax rate            | 16.90%      |               | 16.90%    |            | 25.00%        | It's worth noting that I assumed a 5-year estimate of the starting value of the firm's effective tax rate; it has been fluctuating widely as the firm pivots and is currently at 68% (which is unrealistic and will impact the valuation).                                                                                                                                                                                                                                                                              |
| Reinvestment (c)    | 0.75        |               | 1.50      | 2.00       | 37.74%        | As alluded to above, the firm is still in process of expanding their overseas client base and their systems are rapidly gaining traction and popularity. We expect this expansion to fuel revenue growth as management turns its focus towards profitability. The efficiency of invested capital should increase as customer acquisition should be relatively easier given Salesforce's establishment as a market leader. The revenue generated per dollar reinvestment will increase, improving the firm's cash flows. |
| Return on capital   | 3.92%       | Marginal ROIC |           | 37.47%     | 9.54%         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| Cost of capital (d) |             |               | 10.40%    |            | 9.54%         | Cost of capital close to median company                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |

| The Cash Flows |              |                  |             |             |              |             |
|----------------|--------------|------------------|-------------|-------------|--------------|-------------|
|                | Revenues     | Operating Margin | EBIT        | EBIT (1-t)  | Reinvestment | FCFF        |
| 1              | \$39,190.00  | 10.00%           | \$3,919.00  | \$3,256.69  | \$10,450.67  | -\$7,193.98 |
| 2              | \$47,028.00  | 14.00%           | \$6,583.92  | \$5,471.24  | \$5,225.33   | \$245.90    |
| 3              | \$56,433.60  | 16.00%           | \$9,029.38  | \$7,503.41  | \$6,270.40   | \$1,233.01  |
| 4              | \$67,720.32  | 18.00%           | \$12,189.66 | \$10,129.61 | \$7,524.48   | \$2,605.13  |
| 5              | \$81,264.38  | 20.00%           | \$16,252.88 | \$13,506.14 | \$6,772.03   | \$6,734.11  |
| 6              | \$94,851.79  | 20.00%           | \$18,970.36 | \$15,457.05 | \$6,793.70   | \$8,663.35  |
| 7              | \$107,599.87 | 20.00%           | \$21,519.97 | \$17,185.85 | \$6,374.04   | \$10,811.81 |
| 8              | \$118,532.02 | 20.00%           | \$23,706.40 | \$18,547.89 | \$5,466.07   | \$13,081.82 |
| 9              | \$126,687.02 | 20.00%           | \$25,337.40 | \$19,413.52 | \$4,077.50   | \$15,336.02 |
| 10             | \$131,247.75 | 20.00%           | \$26,249.55 | \$19,687.16 | \$2,280.37   | \$17,406.80 |
| Terminal year  | \$135,972.67 | 20.00%           | \$27,194.53 | \$20,395.90 | \$7,696.57   | \$12,699.33 |

### Intrinsic Value:

| The Value                           |              |  |  |                                 |  |  |
|-------------------------------------|--------------|--|--|---------------------------------|--|--|
| Terminal value                      | \$213,793.51 |  |  |                                 |  |  |
| PV(Terminal value)                  | \$81,377.54  |  |  |                                 |  |  |
| PV (CF over next 10 years)          | \$29,693.16  |  |  |                                 |  |  |
| Value of operating assets =         | \$111,070.70 |  |  |                                 |  |  |
| Adjustment for distress             | \$0.00       |  |  | Probability of failure = 0.00%  |  |  |
| - Debt & Minority Interests         | \$14,879.00  |  |  |                                 |  |  |
| + Cash & Other Non-operating assets | \$12,508.00  |  |  |                                 |  |  |
| Value of equity                     | \$108,699.70 |  |  |                                 |  |  |
| - Value of equity options           | \$0.00       |  |  |                                 |  |  |
| Number of shares                    | 981.00       |  |  |                                 |  |  |
| Value per share                     | \$110.80     |  |  | Stock was trading at = \$188.59 |  |  |

Using the above assumptions regarding the firm's future profitability, growth and risk, I arrived at a **DCF valuation of \$110.80 per share**. This stock is currently trading at \$188.59.

## Relative Sector Pricing

### Assumptions and Inputs:

For the relative pricing, I used a sample of 29 comparable firms in the information technology sector. I exploited the log-log relationships between EV/Sales, the tax rate and growth. I also controlled for the DFR ratios as a proxy for risk.

### Regression Equation: $\ln(EV/Sales) \sim \ln(Tax) + \ln(Growth) + DFR$

Residuals:

|          | Min      | 1Q       | Median  | 3Q      | Max |
|----------|----------|----------|---------|---------|-----|
| -0.80821 | -0.18510 | -0.00184 | 0.14468 | 0.62960 |     |

Coefficients:

|             | Estimate | Std. Error | t value | Pr(> t )     |
|-------------|----------|------------|---------|--------------|
| (Intercept) | 0.77125  | 0.28611    | 2.696   | 0.012383 *   |
| log(Tax)    | -0.49830 | 0.13096    | -3.805  | 0.000816 *** |
| log(Growth) | 0.23224  | 0.12249    | 1.896   | 0.069577 .   |
| DFR         | -0.25011 | 0.07773    | -3.218  | 0.003557 **  |

---

Signif. codes: 0 '\*\*\*' 0.001 '\*\*' 0.01 '\*' 0.05 '.' 0.1 ' ' 1

Using Salesforce's current Tax rate, our growth estimates and the firm's DFR, the regression model produced a fitted EV/Sales of 4.322. Given Salesforce's current sales of 31,352M, debt of 14,879M, cash of 12508M and shares outstanding of 981M, I model returned a price of \$135.71 per share. I didn't include the direct calculations of the regression given the complex nature of the log-log transformations - I used the predict function in R: using the following assumptions: Consensus growth: 0.109, DFR = 0.071, current 1 year effective tax rate = 0.6848.

Price per share = 31,352 \* 4.322 - 14879 + 12508 = 133132.344 / 981 = **\$135.71 per share**

## **Relative Market Pricing**

I priced Salesforce against the market using the US EV/Sales market regression listed on your website, with an r-squared of 0.306.

EV/Sales = 2.32 + 2.60 g + 10.60 Oper Margin -1.40 DFR- 3.50 Tax rate

EV/Sales = 2.32 + 2.60\*.109 + 10.60\*.059 - 1.40\*0.071 - 3.5\*0.6848 = 0.7326

Price per share = 31,352 \* 0.7326 - 14879 + 12508 = 20597.4752 / 981 = **\$21.00 per share**

This figure appears to be abnormally small compared to the intrinsic and relative sector value, although this may have something to do with the most recent year's effective tax rate (used in the regression) being significantly higher than it typically has been either in Salesforce or across the market/sector. Plugging in the 5-year tax rate would result in a market value of \$79.72 per share, which is still very low. This combined with the fact the market regression has a weak correlation leads me to consider the relative sector values as the more useful and significant measure of its true price.

# **Recommendation: SELL**

Based on all metrics, intrinsic and relative valuation, the current market price of Salesforce appears to be fairly overvalued. This was initially surprising to me as Salesforce has grown considerably recently and there has been significant media attention on their recent innovations and acquisitions. However, when I broke down their future growth, operating margins and reinvestment, I found the stock to be significantly overvalued. In order to intrinsically value the stock at current market prices, the firm would need to grow at a rate that I don't think is possible - given that the firm is already well established and their area will only become more competitive in the next decade. With tech stocks, intrinsic value is normally lower than market price due to the presence of optionality. The pricing of the stock at \$135.71 reflects how investors should be valuing the stock given how tech stocks are evaluated. Using this predicted price, the stock is currently overvalued (with investors possibly overestimating the importance of recent acquisitions on the firm's future profitability and growth). With this in mind, I think it's a good time to sell this stock before the market corrects itself.

# **Netflix, Inc.**

#### **Overview / Story for DCF:**

Netflix (NASDAQ: NFLX) is a media company that offers a variety of movies, television shows, and original content through their streaming service. Their service is available on multiple devices including smart TVs, laptops, tablets, and smartphones through their official app for both iOs and Android. The majority of its revenue comes from Netflix's different streaming subscriptions and partnerships, and a small portion comes from advertising. Netflix has been a leader in the streaming service industry for the last decade. However, trouble in recent times with increasing threat of competition and lower renewal rates has left them trying other ways to increase revenue growth (ad-service, sharing limitations etc.). These attempts will continue to grow revenue in the medium-term. As more firms enter the industry, the demand for content will significantly increase as firm's compete to win market share. As a result, we expect Netflix's operating margins to be squeezed and will tighten in the longer term due to higher costs associated with licensing content. Reinvestment in the industry is relatively high due to the high costs of customer acquisition - Netflix is no different. The establishment of the ad-based streaming service will help with customer acquisition and while it will generate revenue, it will also give users a taste of the Netflix experience. With this in mind, the firm's sales/capital ratio will improve slightly but still stay within industry norms in the longer term. Overall, I think this valuation reflects the fact that Netflix has become 'just another one of the streaming services' rather than THE streaming service. That being said, the risk associated with the firm is still relatively low; the firm is profitable and well-established, and that is unlikely to change in the foreseeable future.

## **Intrinsic DCF Valuation Model:**

| The Assumptions      |                 |                 |           |            |               |                                                                                                                                                                                                                                                                                                              |
|----------------------|-----------------|-----------------|-----------|------------|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                      | Base year       | Next year       | Years 2-5 | Years 6-10 | After year 10 | Link to story                                                                                                                                                                                                                                                                                                |
| Revenues (a)         | \$31,615,550.00 | 12.0%           | 12.00%    |            | 3.44%         | Revenue expected to grow as the firm plans the implementation of an ad-based streaming service - increasing their platform users and generating ad-revenue. New rules such as the one-home-only streaming account will seek to increase the platforms number of subscribers.                                 |
| Operating margin (b) | 17.99%          | 20.0%           |           |            | 15.00%        | Margins currently reflect the companies position as a market leader. However, the emergence of competition will squeeze their margins as more players enter the industry. Advertising-based revenue will help to mitigate the decline in profitability but overall margins will decrease in the longer-term. |
| Tax rate             | 15.00%          |                 | 15.00%    |            | 25.00%        | Global/US marginal tax rate over time                                                                                                                                                                                                                                                                        |
| Reinvestment (c)     | 1.50            | 1.50            | 1.50      |            | 38.74%        | Significant reinvestment is always necessary to grow revenue in this sector. I expected sales/capital ratio to stay similar over the next 10 years and improve slightly.                                                                                                                                     |
| Return on capital    | 14.93%          | Marginal ROIC = | 13.02%    |            | 8.88%         |                                                                                                                                                                                                                                                                                                              |
| Cost of capital (d)  |                 |                 | 9.88%     |            | 8.88%         | Cost of capital is relatively high due to the high beta associated with the entertainment industry.                                                                                                                                                                                                          |

|               | The Cash Flows  |                  |                 |                |                |                |
|---------------|-----------------|------------------|-----------------|----------------|----------------|----------------|
|               | Revenues        | Operating Margin | EBIT            | EBIT (1-t)     | Reinvestment   | FCFF           |
| 1             | \$35,409,416.00 | 20.00%           | \$7,081,883.20  | \$6,019,600.72 | \$2,832,753.28 | \$3,186,847.44 |
| 2             | \$39,658,545.92 | 19.00%           | \$7,535,123.72  | \$6,404,855.17 | \$3,172,683.67 | \$3,232,171.49 |
| 3             | \$44,417,571.43 | 18.50%           | \$8,217,250.71  | \$6,984,663.11 | \$3,553,405.71 | \$3,431,257.39 |
| 4             | \$49,747,680.00 | 18.00%           | \$8,954,582.40  | \$7,611,395.04 | \$3,979,814.40 | \$3,631,580.64 |
| 5             | \$55,717,401.60 | 17.50%           | \$9,750,545.28  | \$8,287,963.49 | \$3,821,470.85 | \$4,466,492.64 |
| 6             | \$61,449,607.88 | 17.00%           | \$10,446,433.34 | \$8,670,539.67 | \$3,513,278.91 | \$5,157,260.76 |
| 7             | \$66,719,526.25 | 16.50%           | \$11,008,721.83 | \$8,917,064.68 | \$3,053,085.52 | \$5,863,979.16 |
| 8             | \$71,299,154.53 | 16.00%           | \$11,407,864.73 | \$9,012,213.13 | \$2,448,888.29 | \$6,563,324.84 |
| 9             | \$74,972,486.97 | 15.50%           | \$11,620,735.48 | \$8,947,966.32 | \$1,719,369.03 | \$7,228,597.29 |
| 10            | \$77,551,540.53 | 15.00%           | \$11,632,731.08 | \$8,724,548.31 | \$1,778,515.33 | \$6,946,032.98 |
| Terminal year | \$80,219,313.52 | 15.00%           | \$12,032,897.03 | \$9,024,672.77 | \$3,496,044.41 | \$5,528,628.36 |

|                                     | <i>The Value</i> |  |                                 |  |  |
|-------------------------------------|------------------|--|---------------------------------|--|--|
| Terminal value                      | \$101,629,197.87 |  |                                 |  |  |
| PV(Terminal value)                  | \$40,445,292.25  |  |                                 |  |  |
| PV (CF over next 10 years)          | \$28,355,572.45  |  |                                 |  |  |
| Value of operating assets =         | \$68,800,864.70  |  |                                 |  |  |
| Adjustment for distress             | \$0.00           |  | Probability of failure = 0.00%  |  |  |
| - Debt & Minority Interests         | \$16,756,949.11  |  |                                 |  |  |
| + Cash & Other Non-operating assets | \$5,147,176.00   |  |                                 |  |  |
| Value of equity                     | \$57,191,091.59  |  |                                 |  |  |
| - Value of equity options           | \$1,951,000.00   |  |                                 |  |  |
| Number of shares                    | 445,347.00       |  |                                 |  |  |
| Value per share                     | \$124.04         |  | Stock was trading at = \$322.76 |  |  |

Using the above assumptions regarding the firm's future revenue growth, operating margins and revenue growth, I arrived at an intrinsic valuation of **\$124.04 per share.** This DCF Value per share reflects an overvalued company with declining operating margins.

# **Relative Sector Pricing:**

We used P/BV as the pricing multiple for this regression as it produced the highest R-squared value for the Communication Services sector. I used the same regression analysis that we used for the pricing of Warner Bros Discovery, given that the two firms are in the same industry. The sample size (n = 62) was reduced due to the lack of EPS growth multiples for some firms in the industry. However, we felt that the sample was representative of a similar firm and was large enough to give an accurate representation. The r-squared was 0.66 and the output of the regression is given above (under the Warner Bros Sector Valuation).

Regression equation from above: PBV = -0.729 - 0.002\*gEPS + 0.173\*ROE + 2.403\*Beta

I used the following metrics: Growth EPS: 15%, Return on Equity: 24.5%, Beta: 1.27, Book Value of Equity: 20777401, and shares outstanding: 445,347

PBV = -0.729 - 0.002\*15 + 0.173\*24.5 + 2.403\*1.27 = 6.53.

Price per share: 6.53\*20777401/ 445,347 = **\$304.65**

## **Relative Market Valuation:**

I used the 2023 PBV US market valuation on your website to price Netflix, Inc against the market. The regression has an R-squared of 0.369.

PBV= 2.32 + 4.60 gEPS - 1.33 Beta + 8.90 ROE + 0.80 Payout Ratio

PBV= 2.32 + 4.60\* 0.15 - 1.33\*1.27 + 8.90\*0.15 + 0.80 \* 0 = 2.6559

2.6559 \* 6.53\*20777401/ 445,347 = **\$123.91** price per share

## **Recommendation: Sell**

Up until now, Netflix has been the primary leader in the streaming service industry, with monopoly-like characteristics and huge market share. Over the last 12 months, they've seen a reduction in the level of subscription renewal, and they are likely to face extreme competition from the HBO Max and Discovery merger when it's established. Overall, this will impact netflix's profitability and retention rate on current subscribers. When we priced Netflix against other firms in the Communications Sector, we found that it was overpriced relative to its peers and the US market as a whole. Similarly, the intrinsic DCF valuation produced a significant overvaluation, given my estimates of future growth, operating margins and reinvestment. The increase in the level of competition in the market, will put pressure on Netflix's entire operations. I think the sector pricing of \$304.65 is most reflective of the rightful stock price. We think that now would be a good time to sell before there is a full unveiling of the MAX streaming platform. We feel that the glory days of Netflix as the premier streaming service could be coming to a close.